openapi: '3.0.0'
info: 
  title: Linktree Clone Api
  version: '1.0.0'

servers:
  - url: http://localhost:8080/api

paths: 
  /auth/me: 
    get:
      summary: Authenticate the current user
      tags: 
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'

  /auth/login: 
    post:
      summary: Login a potential user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginInput:
      type: object
      properties:
        username:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
      required:
        - username
        - password
    User:
      type: object
      properties:
        id:
          type: integer
          nullable: false
        username:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        roles:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - roles
    JwtUser:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            accessToken:
              type: string
            tokenType:
              type: string
          required:
            - accessToken
            - tokenType
    Error: 
      type: object
      properties:
        errorCode:
          type: string
        message:
          type: string
        details:
          type: string
        timestamp:
          type: string
        httpStatus:
          type: string
    ApiResponse:
      type: object
      properties:
        user:
          oneOf:
            - $ref: '#/components/schemas/User'
            - $ref: '#/components/schemas/JwtUser'
          nullable: true
        error:
          $ref: '#/components/schemas/Error'
          nullable: true