openapi: '3.0.0'
info: 
  title: Linktree Clone Api
  version: '1.0.0'

servers:
  - url: http://localhost:8080/api

paths: 
  /auth/me: 
    get:
      summary: Authenticate the current user
      tags: 
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'

  /auth/register:
    post:
      summary: Register a user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/UsernameEmailAndPassword'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'
                
  /auth/login: 
    post:
      summary: Login a potential user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/UsernameAndPassword'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'

  /auth/logout:
    post:
      summary: Log out the current user
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiAuthResponse'

  /admin/links:
    get:
      summary: Get all links for the current user
      tags:
        - Links
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLinkResponse'
    
    post:
      summary: Add a new link
      tags:
        - Links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/LinkPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean 
  
  /admin/links/paginated:
    get:
      summary: Get a paginated list of links for the current user
      tags:
        - Links
      parameters:
        - in: query
          name: pageCount
          schema:
            type: integer
        - in: query
          name: pageNumber
          schema: 
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLinkResponse'
      
  /admin/links/paginated-sorted:
    get:
      summary: Get a sorted, paginated list of links for the current user
      tags:
        - Links
      parameters:
        - in: query
          name: pageCount
          schema:
            type: integer
        - in: query
          name: pageNumber
          schema: 
            type: integer
        - in: query
          name: sortKey
          schema:
            type: string
        - in: query
          name: order
          schema: 
            type: string
            enum: [ASC, DESC]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLinkResponse'

  /admin/link/{id}:
    delete:
      summary: Delete a link
      tags:
        - Links
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Numeric ID of the link to be deleted
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean 
                
    put:
      summary: Add a new link
      tags:
        - Links
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the link to be updated
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/LinkPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLinkResponse'

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ApiLinkResponse:
      type: object
      properties:
        data:
          oneOf:
            - $ref: 'links.yaml#/components/schemas/PaginatedResponse'
            - $ref: 'links.yaml#/components/schemas/Link'
        error:
          oneOf:
            - $ref: 'error.yaml#/components/schemas/Error'
            - $ref: 'error.yaml#/components/schemas/MultipleErrors'
          nullable: true

    ApiAuthResponse:
      type: object
      properties:
        data:
          oneOf:
            - $ref: 'auth.yaml#/components/schemas/User'
            - $ref: 'auth.yaml#/components/schemas/JwtUser'
            - $ref: 'error.yaml#/components/schemas/Message'
          nullable: true
        error:
          oneOf:
            - $ref: 'error.yaml#/components/schemas/Error'
            - $ref: 'error.yaml#/components/schemas/MultipleErrors'
          nullable: true
