openapi: '3.0.0'
info: 
  title: Linktree Clone Api
  version: '1.0.0'

servers:
  - url: http://localhost:8080/api

paths: 
  /auth/me: 
    get:
      summary: Authenticate the current user
      tags: 
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'

  /auth/register:
    post:
      summary: Register a user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/UsernameEmailAndPassword'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'
                
  /auth/login: 
    post:
      summary: Login a potential user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/UsernameAndPassword'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'

  /auth/logout:
    post:
      summary: Log out the current user
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ApiResponse'

  /secure/links/all:
    get:
      summary: Get all links for the current user
      tags:
        - Links
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'links.yaml#/components/schemas/Link'
  
  /secure/links/paginated:
    get:
      summary: Get a paginated list of links for the current user
      tags:
        - Links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/PaginatedQuery'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'links.yaml#/components/schemas/Link'
      
  /secure/links/paginated-sorted:
    get:
      summary: Get a sorted, paginated list of links for the current user
      tags:
        - Links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'payload.yaml#/components/schemas/SortedPaginatedQuery'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'links.yaml#/components/schemas/Link'

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ApiResponse:
      type: object
      properties:
        data:
          oneOf:
            - $ref: 'auth.yaml#/components/schemas/User'
            - $ref: 'auth.yaml#/components/schemas/JwtUser'
            - $ref: 'error.yaml#/components/schemas/Message'
          nullable: true
        error:
          oneOf:
            - $ref: 'error.yaml#/components/schemas/Error'
            - $ref: 'error.yaml#/components/schemas/MultipleErrors'
          nullable: true
